import express from "express";
const router = express.Router();

import ProfileRouter from "./profile";
import JobOfferRouter from "./joboffer";
import JobQuestionRouter from "./jobquestion";
import JobApplicationRouter from "./jobapplication";
import JobQuestionAnswerRouter from "./jobquestionanswer";
import CourseRouter from "./course";
import CourseModuleRouter from "./coursemodule";
import LessonRouter from "./lesson";
import CourseEnrollmentRouter from "./courseenrollment";
import LessonProgressRouter from "./lessonprogress";
import LessonResourceRouter from "./lessonresource";
import CourseProgressRouter from "./courseProgress";
import ModuleCertificateRouter from "./modulecertificate";
import QuizRouter from "./quiz";
import QuizQuestionRouter from "./quizquestion";
import QuizAttemptRouter from "./quizattempt";
import QuizAnswerRouter from "./quizanswer";
import CertificateRouter from "./certificate";
import StudentNoteRouter from "./studentnote";
import DiscussionRouter from "./discussion";
import EntrepreneurshipRouter from "./entrepreneurship";
import BusinessPlanRouter from "./businessplan";
import NewsArticleRouter from "./newsarticle";
import NewsRouter from "./news";
import NewsCommentRouter from "./newscomment";
import authRouter from "./auth";
import socketRouter from "./socket";
import UserRouter from "./user";
import RefreshTokenRouter from "./refreshtoken";
import ResourceRouter from "./resource";
import ExternalApiKeyRouter from "./externalapikey";
import MunicipalityRouter from "./municipality";
import MunicipalityAuthRouter from "./municipalityAuth";
import InstitutionRouter from "./institution";
import InstitutionAuthRouter from "./institutionAuth";
import CompanyAuthRouter from "./companyAuth";
import CompanyRouter from "./company";
import AdminRouter from "./admin";
import FileUploadRouter from "./fileUpload";
import CVRouter from "./cv";
import ContactRouter from "./contacts";
import MessageRouter from "./messages";
import JobApplicationMessageRouter from "./jobApplicationMessages";
import YouthApplicationRouter from "./youthapplication";
import YouthProfileRouter from "./youth-profile";

// Register routes
router.use("/profile", ProfileRouter);
router.use("/joboffer", JobOfferRouter);
router.use("/jobquestion", JobQuestionRouter);
router.use("/jobapplication", JobApplicationRouter);
router.use("/jobquestionanswer", JobQuestionAnswerRouter);
router.use("/course", CourseRouter);
router.use("/coursemodule", CourseModuleRouter);
router.use("/lesson", LessonRouter);
router.use("/course-enrollments", CourseEnrollmentRouter);
router.use("/lessonprogress", LessonProgressRouter);
router.use("/lessonresource", LessonResourceRouter);
router.use("/course-progress", CourseProgressRouter);
router.use("/modulecertificate", ModuleCertificateRouter);
router.use("/quiz", QuizRouter);
router.use("/quizquestion", QuizQuestionRouter);
router.use("/quizattempt", QuizAttemptRouter);
router.use("/quizanswer", QuizAnswerRouter);
router.use("/certificate", CertificateRouter);
router.use("/studentnote", StudentNoteRouter);
router.use("/discussion", DiscussionRouter);
router.use("/entrepreneurship", EntrepreneurshipRouter);
router.use("/businessplan", BusinessPlanRouter);
router.use("/newsarticle", NewsArticleRouter);
router.use("/news", NewsRouter);
router.use("/newscomment", NewsCommentRouter);
router.use("/auth", authRouter);
router.use("/socket", socketRouter);
router.use("/user", UserRouter);
router.use("/refreshtoken", RefreshTokenRouter);
router.use("/resource", ResourceRouter);
router.use("/external-api-keys", ExternalApiKeyRouter);
router.use("/municipality", MunicipalityRouter);
router.use("/municipality/auth", MunicipalityAuthRouter);
router.use("/institution", InstitutionRouter);
router.use("/institution/auth", InstitutionAuthRouter);
router.use("/company", CompanyRouter);
router.use("/company/auth", CompanyAuthRouter);
router.use("/admin", AdminRouter);
router.use("/files", FileUploadRouter);
router.use("/cv", CVRouter);
router.use("/contacts", ContactRouter);
router.use("/messages", MessageRouter);
router.use("/jobapplication-messages", JobApplicationMessageRouter);
router.use("/youthapplication", YouthApplicationRouter);
router.use("/youth-profile", YouthProfileRouter);

export default router;
